"""
Package remote Python source and configuration into Kaggle's single code file.
"""

import json
from pathlib import Path


# ----------------------------------------------------------------------------------------------------------------------
# Remote source packaging


def prepare_kernel(
    root: Path,
    metadata: dict,
    output: Path | None = None,
    job_args: list[str] | None = None,
) -> Path:
    """
    Generate a standalone Kaggle script and its metadata.

    Embed the remote job package and configuration so imports work on Kaggle. Keep local launcher settings outside the
    payload and leave source metadata unchanged.

    :param root: Repository root containing src/training/job.
    :param metadata: Resolved Kaggle environment metadata.
    :param output: Optional build destination; defaults to build/kaggle.
    :param job_args: Optional pipeline argument tokens passed to the remote entry point.

    :return: Directory ready for kaggle kernels push.
    """
    # ------------------------------------------------------------------------------------------------------------------
    # Capture remote source and configuration files

    # Resolve the local package containing code permitted to run remotely
    package = root / "src/training"

    # Start with a minimal package initializer rather than copying local launcher imports.
    payload = {"training/__init__.py": '"""Remote training package."""\n'}

    # Collect source and configuration deterministically for reproducible builds
    for source in sorted((package / "job").rglob("*")):
        if source.is_file() and source.suffix in {
            ".py",
            ".json",
            ".yaml",
            ".yml",
        }:
            if "__pycache__" not in source.parts:
                payload[source.relative_to(package.parent).as_posix()] = (
                    source.read_text(encoding="utf-8")
                )

    # Refuse to create a package that Kaggle cannot execute
    if "training/job/execute.py" not in payload:
        raise ValueError("Missing remote entry point: job/execute.py")

    # ------------------------------------------------------------------------------------------------------------------
    # Generate the Kaggle bootstrap script

    # Kaggle uploads code_file, so embed the remote tree to preserve local imports.
    # Restore the embedded package inside Kaggle before importing its entry point
    script = (
        "# Generated by training-submit prepare. "
        "Edit src/training/job instead.\n"
        "# --------------------------------------------------------------\n"
        "# Import standard library functionality\n\n"
        "import json\nimport sys\nimport tempfile\nfrom pathlib import Path\n\n"
        "# --------------------------------------------------------------\n"
        "# Capture packaged source files\n\n"
        f"SOURCES = json.loads({json.dumps(payload)!r})\n\n"
        "# --------------------------------------------------------------\n"
        "# Restore the package and execute the remote pipeline\n\n"
        "with tempfile.TemporaryDirectory(prefix='training_') as directory:\n"
        "    root = Path(directory)\n"
        "    for relative, content in SOURCES.items():\n"
        "        target = root / relative\n"
        "        target.parent.mkdir(parents=True, exist_ok=True)\n"
        "        target.write_text(content, encoding='utf-8')\n"
        "    sys.path.insert(0, str(root))\n"
        "    from training.job.execute import main\n"
        f"    main({job_args or []!r})\n"
    )

    # ------------------------------------------------------------------------------------------------------------------
    # Write the generated script and Kaggle metadata

    # Use the standard build directory unless the caller supplies another
    # destination
    output = output if output is not None else root / "build/kaggle"
    output.mkdir(parents=True, exist_ok=True)

    # Match metadata to the generated bootstrap without modifying the source mapping.
    prepared_metadata = dict(metadata)
    prepared_metadata.update(
        code_file="run.py", language="python", kernel_type="script"
    )

    # Write only the bootstrap and metadata required by kaggle kernels push
    (output / "run.py").write_text(script, encoding="utf-8")
    (output / "kernel-metadata.json").write_text(
        json.dumps(prepared_metadata, indent=2) + "\n", encoding="utf-8"
    )

    return output
